patterns: list[tuple[str, str]] = [
    ('if_reserved', 'if'),
    ('else_reserved', 'else'),
    ('number_reserved', 'number'),
    ('string_reserved', 'string'),
    ('while_reserved', 'while'),
    ('for_reserved', 'for'),
    ('output_reserved', 'output'),
    ('input_reserved', 'input'),
    ('in_reserved', 'in'),
    ('bool_reserved', 'bool'),
    ('true', 'true'),
    ('false', 'false'),
    ('op', '('),
    ('cp', ')'),
    ('gt', '>'),
    ('attr', '='),
    ('equal', '=='),
    ('gte', '>='),
    ('lte', '<='),
    ('lt', '<'),
    ('open_curly_braces', '{'),
    ('close_curly_braces', '}'),
    ('string', '".*"'),
    ('add', '+'),
    ('sub', '-'),
    ('mult', '*'),
    ('div', '/'),
    ('number', '(0-9)+ | (0-9)*.(0-9)+'),
    ('id', '(a-z|A-Z)(a-z|A-Z|0-9|_)*'),
]

unique_patterns: list[tuple[str, str]] = [
    ('op', '('),
    ('cp', ')'),
    ('add', '+'),
    ('sub', '-'),
    ('mult', '*'),
    ('div', '/'),
    ('open_curly_braces', '{'),
    ('close_curly_braces', '}'),
    ('gt', '>'),
    ('attr', '='),
    ('equal', '=='),
    ('gte', '>='),
    ('lte', '<='),
    ('lt', '<'), 
]
